# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed


# Chulapa docs: https://dieghernan.github.io/chulapa/docs/02-config

# XX. Installing Chulapa
# These settings were copied and modified from https://github.com/dieghernan/chulapa/blob/master/_config.yml

# With remote theme
remote_theme: dieghernan/chulapa

# With gem based method do this instead
#theme: chulapa-jekyll
# And at this to your Gemfile
# gem install 'chulapa-jekyll'

# A. Site Settings /SEO options
# Overall options for your site, would affect your site SEO
# Default values are explained
locale                  :     #default["en-US"] format language-TERRITORY , e.g fr, en-GB, es-MX, pt-BR
title                   :     Quantum Secrets 
title_separator         :     #default [" | "]
subtitle                :     #default [your-repository-tagline]
description             : >- # this means to ignore newlines until "baseurl:"
  Welcome to Quantum Secrets, the most enigmatic and cutting-edge quantum 
  company in the world. We specialize in revolutionary quantum technology, 
  pushing the limits of what's possible. We won't tell you much more than that, as we can't reveal our secrets to just anyone.
url                     :     'https://quantumsecrets.dev' #See baseurl - On Github Pages you may leave it blank - If you use CNAME use your domain
baseurl                 :     #On Github Pages you may leave it blank. Have a look to: https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
words_per_minute        :     #default[200]
timezone                :     #"Europe/Madrid ,see https://jekyllrb.com/docs/configuration/options/ and https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# SEO
og_image                :     /assets/img/quantumsecrets_b_300.png #default[author.avatar (see below)] or [github-avatar]
twitter_site            :     #Avoid @
author:
  name                  :     Quantum Secrets # Name Surname Company
  avatar                :     /assets/img/quantumsecrets_logo_w.svg # Try a square file. Info: Your github avatar on https://github.com/[USERNAME].png
  location              :     "New York, USA"
  links:
    - url:  thequantumsecret+post@gmail.com #A link or email: https://twitter.com/jack, mail@example.com
      icon: fas fa-envelope # A Fontawesome code: fab fa-twitter - see https://fontawesome.com/
      label: Email # A Label for the icon: Twitter
    - url:  https://www.linkedin.com/in/schnabel/ # Another link
      icon: fab fa-linkedin # Another FontAwesome code
      label: LinkedIn # Another label

fa_version: #default ["6"] Use 6 or 5
fa_kit_code: 82d444c920 # Your FontAwesome kit code. If not provided a free hosted version (slower) will be loaded:  https://fontawesome.com/
fa_v4_support: #Bool Add FontAwesome 4 support

# Web tracking - Google services https://analytics.google.com/analytics/web/
gtag_id                 : 'G-W6NX353187'

# Search providers
# Available free search engines:
# - lunr https://lunrjs.com/
# - algolia v4 https://www.algolia.com/ - needs further configuration
# - google custom search engine https://cse.google.es/
search:
  provider              : google #Select a provider for enable search: lunr, algolia, google
  label                 :  #default ["Search"] Text on navbar when search is enabled
  landing_page          :  #default ["/search"] Link on navbar
  lunr_maxwords         :  #default [30] lunr only - May slow down your site build
  algolia_logo          :  true #Displays algolia logo. Should be set to true if you are on a community plan, otherwise false.

#Google search settings
google_cse_id: c5e579fa7b97b4f29 #Your cse id


#Comments settings
comments:
  provider:         #Enable comments via Disqus, giscus, Cactus.chat, cusdis
  disqus_shortname: #Your site id : check your address https://{{ disqus.shortname }}.disqus.com/admin/
  cactus_shortname: #Your site id as registered with Cactus.chat
  cusdis_app_id:    # Your cusdis app id
  cusdis_host:      # Optionally you can use your own host
  website_id:       # Welcomments id
  


# B. Navigation
# Configure your navbar and the footer of your site

# Navbar:
#   "brand" options would be set on the left side of your navbar
#   "nav" would be set on the right side. Two-level nav links available
navbar:
  style     :  #default is the classical top navbar, set "fab" for a floating action button navbar or "dual"
  expand    :  # At which device size expand the navbar menu. default[md] https://getbootstrap.com/docs/4.5/layout/overview/
  brand:
    title   :  Quantum Secrets # Title in navbar
    url     :  # default["url/baseurl"]
    img     :  /assets/img/quantumsecrets_logo_w.svg # An small image, try 30x30px
  nav:
  - title   : About 
    url     : /about/ 
  - title   : Product
    url     : /product/
  - title   : Careers
    url     : /careers/
  - title   : Podcast
    url     : /podcast/      
#  - title   : # Label submenu
#    child:
#     - title: # Child label
#       url  : # child url
#     - title: # Child label
#       url  : # child url

#Social links to be placed on your site footer
footer:
  links:
    - label : LinkedIn
      icon  : "fab fa-linkedin" 
      url   : https://www.linkedin.com/in/schnabel/ 
    - label : Contact
      icon  : "fas fa-envelope" 
      url   : thequantumsecret+webfooter@gmail.com
    - label: "RSS"
      icon: "fas fa-rss"
      url:  "./atom.xml"      
  copyright: '&copy; 2023 Quantum Secrets'


# C. Theme Settings
# Google Fonts https://fonts.google.com/, add as many as you need
googlefonts:
 # - url : # 'https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap'

# Theme and colors
chulapa-skin:
  highlight     :  'default' # default["default"]
  skin          :  'deeply' # Optional predefined skins
  autothemer    :  'true' # Bool: Use autotheming
#  vars          :
#    primary     :  ["#0D1B2A"] # Dark Blue
#   body-bg     :
#   body-color  :
#   font-family-base :



# D. Jekyll Defaults and collections: see https://jekyllrb.com/

# Blog pagination: on this site /blog/index.html. https://jekyllrb.com/docs/pagination/
#paginate: 4
#paginate_path: "/blog/page:num/"
#paginator_maxnum: 3  #default[3] Custom: max of number to be displayed on the paginator


# Collections https://jekyllrb.com/docs/step-by-step/09-collections/
collections:
  homepage_cards:
#  demo:
#    output: true
#    permalink: /demo/:name
#  docs:
#    output: true
#    permalink: /docs/:name
#  skins:
#    output: true
#    permalink: /skins/:name
#collections_dir     : docs/collections
permalink           : /:year:month:day_:title/


# Defaults https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      header_type: "base"
      include_on_search   : false
      cloudtag_url        : /tags/ #This is where the link on tags would redirect
      cloudcategory_url   : /categories/ #This is where the link on categories would redirect
  -
    scope:
      path: ""
      type: "posts"
    values:
      header_type       : "post"
      include_on_search : true
      include_on_feed   : true
      show_date         : true
      show_related      : true
      show_bottomnavs   : true
      show_sociallinks  : true
      show_comments     : true
      show_tags         : false
      show_categories   : false
      show_author       : true
      show_toc          : false
  -
    scope:
      path: ""
      type: "demo"
    values:
      header_type       : "hero"
      show_related      : true
      show_bottomnavs   : true
      show_sociallinks  : true
      include_on_search : true
      include_on_feed   : true




# XX. Other settings - no need to modify
# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  blanklines: true

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap

# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor
  - /docs # ignore Chulapa /docs
  - /test # ignore Chulapa /test
  - github-metrics.svg

include:
 - _pages

# Conversion
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style










# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
